sudo: true

language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - gcc-4.8
      - g++-4.8

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tst/tst_host/vector_host_test

notifications:
email: true
